# application: reprint-sunkit-hokkaido
# version: 2
runtime: php55 # Replace with php74 to use PHP 7.4
api_version: 1
threadsafe: true

handlers:
# Serve a directory as a static resource.
- url: /style
  mime_type: text/css
  static_dir: style

- url: /(\w*)/style/(.*\.css)$
  mime_type: text/css
  static_files: \1/style/\2
  upload: (\w*)/style/(.*\.css)$

# Serve images as static resources.
- url: /js
  mime_type: text/javascript
  static_dir: js

- url: /images
  static_dir: images

- url: /(\w*)/images/(.*\.(gif|png|jpg|jpeg))
  static_files: \1/images/\2
  upload: (\w*)/images/(.*\.(gif|png|jpg|jpeg))

- url: /newphoto
  static_dir: newphoto

- url: /(\w*)/newphoto/*/(.*\.(gif|png|jpg|jpeg))
  static_files: \1/newphoto/\2
  upload: (\w*)/newphoto/*/(.*\.(gif|png|jpg|jpeg))

- url: /recommend_files
  static_dir: recommend_files

- url: /recommend_files
  static_files: \1/recommend_files/\2
  upload: (\w*)/recommend_files/(.*\.html)$

# Serve your app through a front controller at index.php or public/index.php.
- url: /.*
  script: auto